import { termBadge } from '@/domain/rewards';
import { colours } from '@/theme/tokens';
import { buildTopic, collect, listenChoose, select } from './authoring';
import { scienceTopic } from './nsHelpers';

const C = colours.clay;
const fuels = scienceTopic({ id: 't3-energy-in-fuels', term: 3, area: 'ENE', title: 'Energy In Fuels', emoji: '🔥', atpWeeks: 3, colour: C, text: 'Energy is stored in fuels such as coal, wood, petrol, paraffin, gas and candle wax. Burning can give heat and light.', factRef: 'fuel-energy', skills: ['observe', 'compare', 'investigate'], kit: ['paper'], makeTask: 'Watch a grown-up demonstrate a safe fuel investigation.' });
const electricity = scienceTopic({ id: 't3-energy-electricity', term: 3, area: 'ENE', title: 'Energy And Electricity', emoji: '🔌', atpWeeks: 3, colour: C, text: 'A cell stores energy. A complete circuit gives electrical energy a path through a bulb. Wall sockets are not for children.', factRef: 'simple-circuits', skills: ['observe', 'design', 'make'], kit: ['torch cell', 'wire', 'bulb'], makeTask: 'Make a complete simple circuit with a torch cell, wire and bulb.' });
const movement = scienceTopic({ id: 't3-stored-energy-movement', term: 3, area: 'ENE', title: 'Stored Energy That Moves', emoji: '🪀', atpWeeks: 2, colour: C, text: 'A stretched elastic or compressed spring stores energy. When it is released, stored energy can cause movement.', factRef: 'stored-energy-movement', skills: ['design', 'make', 'evaluate'], kit: ['elastic band', 'paper', 'card'], makeTask: 'Make a safe elastic-powered object that moves on a table.' });
const challenge = buildTopic({ id: 't3-star-challenge', term: 3, weeks: [9, 9], atpWeeks: 0, area: 'ENE', atpHours: 0, requires: [], teaches: [], skills: [], title: 'Term 3 Star Challenge', emoji: '⭐', colour: C, parentNote: 'A friendly review of Energy and Change. Finishing earns three stars.', badge: { emoji: '⭐', title: 'Term 3 Science Star' }, words: [], textTypes: [], lessons: [{ id: 'challenge', title: 'Term 3 Star Challenge', emoji: '⭐', kind: 'challenge', badge: termBadge(3, 'Term 3 Science Star'), activities: [select('a1', 'Tap the stored energy source.', 'one', [['a', '🪵', 'fuel', true], ['b', '🪨', 'ordinary stone', false]]), listenChoose('a2', 'Choose the circuit idea.', [['q', 'What makes a complete circuit?', [['a', '🔁', 'a closed path'], ['b', '🧵', 'a loose piece of thread', 'A circuit needs a closed path.']], 'a']]), select('a3', 'Tap the safe electricity action.', 'one', [['a', '🔋', 'use a torch cell in a model', true], ['b', '🔌', 'put something into a wall socket', false]]), select('a4', 'Tap the stored energy example.', 'one', [['a', '🪀', 'a stretched elastic', true], ['b', '🫗', 'still water in a cup', false]]), select('a5', 'Tap the honest science idea.', 'one', [['a', '👀', 'observe a real result', true], ['b', '🎭', 'pretend the phone did it', false]])] }] });
export const TERM_3 = collect([fuels, electricity, movement, challenge]);
