import { termBadge } from '@/domain/rewards';
import { colours } from '@/theme/tokens';
import { buildTopic, collect, listenChoose, select, sequence } from './authoring';
import { scienceTopic } from './nsHelpers';

const C = colours.teal;
const metals = scienceTopic({ id: 't2-metals-non-metals', term: 2, area: 'MAT', title: 'Metals And Non-Metals', emoji: '⚙️', atpWeeks: 2.5, colour: C, text: 'Metals can be shiny, hard, strong, malleable and ductile. Non-metals often have different properties.', factRef: 'metal-properties', skills: ['observe', 'compare', 'classify'], kit: ['paper', 'pencil'], makeTask: 'Investigate and compare safe metal and non-metal objects.' });
const metalUses = scienceTopic({ id: 't2-what-metals-can-do', term: 2, area: 'MAT', title: 'What Metals Can Do', emoji: '🧲', atpWeeks: 2.5, colour: C, text: 'Some metals conduct heat, some are magnetic, and iron can rust when it meets air and water.', factRef: 'metal-properties', skills: ['observe', 'compare', 'investigate'], kit: ['magnet', 'paper', 'nail'] });
const newMaterials = scienceTopic({ id: 't2-making-new-materials', term: 2, area: 'MAT', title: 'Making New Materials', emoji: '🧱', atpWeeks: 2.5, colour: C, text: 'People process materials by mixing, setting, drying or cooking to make new materials with new properties.', factRef: 'processed-materials', skills: ['plan', 'make', 'evaluate'], kit: ['water', 'paper', 'soil'], makeTask: 'Mix and set a safe material with an adult nearby.' });
const materialsMade = scienceTopic({ id: 't2-materials-we-make', term: 2, area: 'MAT', title: 'Materials We Make', emoji: '🏺', atpWeeks: 1.5, colour: C, text: 'Glass, plastic, fabric, ceramics, paint, plaster and concrete are processed materials people make and use.', factRef: 'processed-materials', skills: ['classify', 'communicate'], kit: ['paper'] });
const challenge = buildTopic({ id: 't2-star-challenge', term: 2, weeks: [10, 10], atpWeeks: 0, area: 'MAT', atpHours: 0, requires: [], teaches: [], skills: [], title: 'Term 2 Star Challenge', emoji: '⭐', colour: C, parentNote: 'A friendly review of Matter and Materials. Finishing earns three stars.', badge: { emoji: '⭐', title: 'Term 2 Science Star' }, words: [], textTypes: [], lessons: [{ id: 'challenge', title: 'Term 2 Star Challenge', emoji: '⭐', kind: 'challenge', badge: termBadge(2, 'Term 2 Science Star'), activities: [select('a1', 'Tap the metal property.', 'one', [['a', '✨', 'shiny', true], ['b', '🌱', 'growing', false]]), sequence('a2', 'Put the material process in order.', [['a', '🥣', 'mix'], ['b', '⏳', 'set'], ['c', '🧱', 'use']]), listenChoose('a3', 'Choose the processed material.', [['q', 'Which is processed?', [['a', '🧱', 'concrete'], ['b', '🪨', 'a natural stone', 'Concrete is made by people.']], 'a']]), select('a4', 'Tap the safe observation.', 'one', [['a', '🧲', 'use a magnet on a safe object', true], ['b', '🔥', 'touch a hot surface', false]]), select('a5', 'Tap the idea about rust.', 'one', [['a', '🔩', 'iron can rust', true], ['b', '🍎', 'all fruit rusts', false]])] }] });
export const TERM_2 = collect([metals, metalUses, newMaterials, materialsMade, challenge]);
