import { termBadge } from '@/domain/rewards';
import { colours } from '@/theme/tokens';
import { buildTopic, collect, listenChoose, select } from './authoring';
import { scienceTopic } from './nsHelpers';

const C = colours.purple;
const earthMoves = scienceTopic({ id: 't4-earth-moves', term: 4, area: 'EAR', title: 'The Earth Moves', emoji: '🌍', atpWeeks: 1.5, colour: C, text: 'The Earth orbits the Sun. About 365 days make one year and the Earth spins on its axis.', factRef: 'earth-year-day', skills: ['observe', 'communicate'], kit: ['paper', 'pencil'], makeTask: 'Make a labelled paper model of the Earth and its orbit.' });
const ground = scienceTopic({ id: 't4-ground-beneath-us', term: 4, area: 'EAR', title: 'The Ground Beneath Us', emoji: '🪨', atpWeeks: 2, colour: C, text: 'Soil contains rock particles, air, water and humus. Sandy, clayey and loamy soils support life in different ways.', factRef: 'soil-types', skills: ['observe', 'compare', 'investigate'], kit: ['soil', 'water', 'paper'] });
const rocks = scienceTopic({ id: 't4-rocks-remember', term: 4, area: 'EAR', title: 'Rocks That Remember', emoji: '🪨', atpWeeks: 2, colour: C, text: 'Sedimentary rocks form in layers over a very long time. Limestone, sandstone and shale are sedimentary rocks.', factRef: 'sedimentary-rocks', skills: ['observe', 'classify', 'communicate'], kit: ['paper', 'pencil'] });
const fossils = scienceTopic({ id: 't4-fossils', term: 4, area: 'EAR', title: 'Fossils', emoji: '🦕', atpWeeks: 2.5, colour: C, text: 'A fossil is evidence of an ancient plant or animal preserved in rock. South Africa has a rich fossil record.', factRef: 'south-african-fossils', skills: ['observe', 'make', 'evaluate'], kit: ['play-dough', 'paper'], makeTask: 'Make a fossil impression in play-dough and label it.' });
const challenge = buildTopic({ id: 't4-star-challenge', term: 4, weeks: [9, 9], atpWeeks: 0, area: 'EAR', atpHours: 0, requires: [], teaches: [], skills: [], title: 'Term 4 Star Challenge', emoji: '⭐', colour: C, parentNote: 'A friendly review of Planet Earth and Beyond. Finishing earns three stars.', badge: { emoji: '⭐', title: 'Term 4 Science Star' }, words: [], textTypes: [], lessons: [{ id: 'challenge', title: 'Term 4 Star Challenge', emoji: '⭐', kind: 'challenge', badge: termBadge(4, 'Term 4 Science Star'), activities: [listenChoose('a1', 'Choose the year idea.', [['q', 'About how many days are in a year?', [['a', '🌍', '365 days'], ['b', '🕐', '24 days', 'A day is about 24 hours; a year is about 365 days.']], 'a']]), select('a2', 'Tap the soil type.', 'one', [['a', '🌱', 'loamy soil', true], ['b', '🍬', 'candy', false]]), select('a3', 'Tap the sedimentary rock.', 'one', [['a', '🪨', 'sandstone', true], ['b', '💎', 'a cut gem', false]]), select('a4', 'Tap the fossil idea.', 'one', [['a', '🦕', 'evidence of ancient life', true], ['b', '🚗', 'a new car', false]]), select('a5', 'Tap the safe making material.', 'one', [['a', '🟤', 'play-dough', true], ['b', '🔥', 'a flame', false]])] }] });
export const TERM_4 = collect([earthMoves, ground, rocks, fossils, challenge]);
